matrix:
    include:
    - os: osx
      osx_image: xcode8.3
      env:
        - DEPLOY_SDIST=true
      install:
        - brew install swig
        - brew upgrade python
        - curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/install_miniconda.sh
        - bash ~/install_miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - which conda
        - conda install -y python==3.6
         
      script: 
        - ./build_and_deploy.sh


    - os: linux
      env:
        - PYTHON_VER=3.5
      install: 
        - docker build -t box2d-py-img -f dockerfile.${PYTHON_VER} . 
      script: 
        - docker run -e TRAVIS_TAG=$TRAVIS_TAG -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD box2d-py-img bash ./build_and_deploy.sh
    

    - os: linux
      env:
        - PYTHON_VER=3.6
      install: 
        - docker build -t box2d-py-img -f dockerfile.${PYTHON_VER} . 
      script: 
        - docker run -e TRAVIS_TAG=$TRAVIS_TAG -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD box2d-py-img bash ./build_and_deploy.sh


    - os: linux
      env:
        - PYTHON_VER=3.7
      install: 
        - docker build -t box2d-py-img -f dockerfile.${PYTHON_VER} . 
      script: 
        - docker run -e TRAVIS_TAG=$TRAVIS_TAG -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD box2d-py-img bash ./build_and_deploy.sh

