matrix:

    - os: linux
      env:
        - REPO_DIR=$PWD
        - BUILD_COMMIT=$TRAVIS_COMMIT
        - PLAT=x86_64

      install: 
        - git clone https://github.com/matthew-brett/multibuild ../multibuild
        - . ../multibuild/common_utils.sh
        - . ../multibuild/travis_steps.sh
        - before_install 
        - clean_code $REPO_DIR $BUILD_COMMIT
        - build_wheel $REPO_DIR $PLAT
      script: 
        - install_run $PLAT
    


